/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.59
 * Generated at: 2026-09-20 04:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.Map;

public final class admin_002dstatistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Map");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Include Admin Left Sidebar -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "SellerHome.html", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    // Ensure Statistics tab is marked active\r\n");
      out.write("    if (typeof activeTab !== 'undefined') {\r\n");
      out.write("        activeTab = 'statistics';\r\n");
      out.write("    }\r\n");
      out.write("    var statTab = document.getElementById('statistics');\r\n");
      out.write("    if (statTab) {\r\n");
      out.write("        statTab.classList.add('active');\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Chart.js CDN -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<main class=\"bookshelf-canvas\" style=\"padding-top: 26px;\">\r\n");
      out.write("  <div class=\"bookshelf-page-container\" style=\"max-width: 1340px; margin: 0 auto;\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Dashboard Top Bar -->\r\n");
      out.write("    <div class=\"dashboard-topbar-flex\">\r\n");
      out.write("      <div class=\"dashboard-title-box\">\r\n");
      out.write("        <span class=\"dashboard-pill-tag\">\r\n");
      out.write("          <svg width=\"13\" height=\"13\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><polyline points=\"12 6 12 12 16 14\"></polyline></svg>\r\n");
      out.write("          Phân tích Điều hành\r\n");
      out.write("        </span>\r\n");
      out.write("        <h1>Thống kê & Hiệu quả Cửa hàng</h1>\r\n");
      out.write("        <p>Theo dõi giao dịch trực tiếp, biểu đồ doanh thu và giám sát kho sách.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div style=\"display:flex; gap:12px; align-items:center; flex-wrap:wrap;\">\r\n");
      out.write("        <span style=\"background:#fff; border:1px solid rgba(197,137,64,0.25); border-radius:var(--radius-pill); padding:8px 16px; font-size:0.85rem; font-weight:600; color:var(--text-secondary); box-shadow:0 2px 8px rgba(0,0,0,0.03);\">\r\n");
      out.write("          📅 ");
      out.print( new java.text.SimpleDateFormat("EEEE, dd/MM/yyyy", new java.util.Locale("vi", "VN")).format(new java.util.Date()) );
      out.write("\r\n");
      out.write("        </span>\r\n");
      out.write("        <a href=\"storebooks\" class=\"nav-pill-btn\" style=\"background:#fff; font-size:0.86rem; padding:8px 18px;\">Danh mục</a>\r\n");
      out.write("        <a href=\"addbook\" class=\"nav-pill-btn\" style=\"background:var(--accent-primary); color:#fff; border-color:var(--accent-primary); font-size:0.86rem; padding:8px 18px;\">+ Thêm sách</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- KPI Cards Grid -->\r\n");
      out.write("    <div class=\"stats-kpi-grid\">\r\n");
      out.write("      <!-- Card 1: Revenue -->\r\n");
      out.write("      <div class=\"stat-kpi-card\">\r\n");
      out.write("        <div class=\"stat-kpi-header\">\r\n");
      out.write("          <span class=\"stat-kpi-label\">Tổng Doanh Thu</span>\r\n");
      out.write("          <div class=\"stat-kpi-icon-box icon-emerald\">\r\n");
      out.write("            <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"12\" y1=\"1\" x2=\"12\" y2=\"23\"></line><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path></svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-value\">\r\n");
      out.write("          ");
      out.print( String.format("%,.0f đ", (Double)request.getAttribute("totalRevenue")) );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-footer\">\r\n");
      out.write("          <span class=\"stat-trend-badge trend-up\">▲ Hoạt động</span>\r\n");
      out.write("          <span>Từ các đơn hoàn tất</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Card 2: Total Orders -->\r\n");
      out.write("      <div class=\"stat-kpi-card\">\r\n");
      out.write("        <div class=\"stat-kpi-header\">\r\n");
      out.write("          <span class=\"stat-kpi-label\">Tổng Đơn Hàng</span>\r\n");
      out.write("          <div class=\"stat-kpi-icon-box icon-blue\">\r\n");
      out.write("            <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z\"></path><line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line><path d=\"M16 10a4 4 0 0 1-8 0\"></path></svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-value\">\r\n");
      out.write("          ");
      out.print( request.getAttribute("totalOrders") );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-footer\">\r\n");
      out.write("          <span class=\"stat-trend-badge trend-up\">▲ Đơn hàng</span>\r\n");
      out.write("          <span>Khách đã thanh toán</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Card 3: Books Sold -->\r\n");
      out.write("      <div class=\"stat-kpi-card\">\r\n");
      out.write("        <div class=\"stat-kpi-header\">\r\n");
      out.write("          <span class=\"stat-kpi-label\">Số Sách Đã Bán</span>\r\n");
      out.write("          <div class=\"stat-kpi-icon-box icon-purple\">\r\n");
      out.write("            <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 19.5A2.5 2.5 0 0 1 6.5 17H20\"></path><path d=\"M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z\"></path></svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-value\">\r\n");
      out.write("          ");
      out.print( request.getAttribute("totalBooksSold") );
      out.write(" <span style=\"font-size:0.9rem; font-weight:600; color:var(--text-secondary);\">cuốn</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-footer\">\r\n");
      out.write("          <span class=\"stat-trend-badge trend-neutral\">&bull; Sản lượng</span>\r\n");
      out.write("          <span>Tổng số bản đã xuất</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Card 4: Customers -->\r\n");
      out.write("      <div class=\"stat-kpi-card\">\r\n");
      out.write("        <div class=\"stat-kpi-header\">\r\n");
      out.write("          <span class=\"stat-kpi-label\">Khách Hàng</span>\r\n");
      out.write("          <div class=\"stat-kpi-icon-box icon-amber\">\r\n");
      out.write("            <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2\"></path><circle cx=\"9\" cy=\"7\" r=\"4\"></circle><path d=\"M23 21v-2a4 4 0 0 0-3-3.87\"></path><path d=\"M16 3.13a4 4 0 0 1 0 7.75\"></path></svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-value\">\r\n");
      out.write("          ");
      out.print( request.getAttribute("totalCustomers") );
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-footer\">\r\n");
      out.write("          <span class=\"stat-trend-badge trend-up\">▲ Độc giả</span>\r\n");
      out.write("          <span>Tài khoản đã đăng ký</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Card 5: Inventory Stock -->\r\n");
      out.write("      <div class=\"stat-kpi-card\">\r\n");
      out.write("        <div class=\"stat-kpi-header\">\r\n");
      out.write("          <span class=\"stat-kpi-label\">Tồn Kho Hiện Tại</span>\r\n");
      out.write("          <div class=\"stat-kpi-icon-box icon-teal\">\r\n");
      out.write("            <svg width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path><polyline points=\"3.27 6.96 12 12.01 20.73 6.96\"></polyline><line x1=\"12\" y1=\"22.08\" x2=\"12\" y2=\"12\"></line></svg>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-value\">\r\n");
      out.write("          ");
      out.print( request.getAttribute("totalStock") );
      out.write(" <span style=\"font-size:0.9rem; font-weight:600; color:var(--text-secondary);\">cuốn</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"stat-kpi-footer\">\r\n");
      out.write("          <span class=\"stat-trend-badge trend-neutral\">");
      out.print( request.getAttribute("totalTitles") );
      out.write(" Đầu sách</span>\r\n");
      out.write("          <span>Đang bày bán trong kho</span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Charts Row 1: Revenue Timeline & Order Status -->\r\n");
      out.write("    <div class=\"stats-charts-row\">\r\n");
      out.write("      <!-- Area Chart: Revenue Trend -->\r\n");
      out.write("      <div class=\"chart-card\">\r\n");
      out.write("        <div class=\"chart-card-header\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3 class=\"chart-card-title\">Biểu đồ Tăng trưởng Doanh thu</h3>\r\n");
      out.write("            <p class=\"chart-card-subtitle\">Doanh thu và xu hướng giao dịch theo các mốc thời gian gần nhất</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div style=\"display:flex; gap:8px;\">\r\n");
      out.write("            <span style=\"font-size:0.75rem; font-weight:700; background:rgba(197,137,64,0.14); color:var(--accent-hover); padding:4px 10px; border-radius:var(--radius-pill);\">\r\n");
      out.write("              ● Doanh thu (đ)\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chart-box-relative\">\r\n");
      out.write("          <canvas id=\"revenueSplineChart\"></canvas>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Doughnut Chart: Order Status Breakdown -->\r\n");
      out.write("      <div class=\"chart-card\">\r\n");
      out.write("        <div class=\"chart-card-header\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3 class=\"chart-card-title\">Trạng thái Đơn hàng</h3>\r\n");
      out.write("            <p class=\"chart-card-subtitle\">Tỷ lệ xử lý & hoàn tất</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chart-box-relative\" style=\"display:flex; align-items:center; justify-content:center;\">\r\n");
      out.write("          <canvas id=\"orderStatusDoughnutChart\" style=\"max-height: 270px;\"></canvas>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Charts Row 2: Top Selling Books Bar Chart & Quick Metrics -->\r\n");
      out.write("    <div class=\"stats-charts-row\" style=\"grid-template-columns: 1.6fr 1fr;\">\r\n");
      out.write("      <!-- Bar Chart: Bestselling Books -->\r\n");
      out.write("      <div class=\"chart-card\">\r\n");
      out.write("        <div class=\"chart-card-header\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3 class=\"chart-card-title\">Top 5 Tựa Sách Bán Chạy Nhất</h3>\r\n");
      out.write("            <p class=\"chart-card-subtitle\">Những đầu sách có số lượng tiêu thụ cao nhất</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <span style=\"font-size:0.75rem; font-weight:700; background:rgba(16,185,129,0.12); color:#059669; padding:4px 10px; border-radius:var(--radius-pill);\">\r\n");
      out.write("            Sản Phẩm Xuất Sắc Nhất\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"chart-box-relative\">\r\n");
      out.write("          <canvas id=\"topBooksBarChart\"></canvas>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Quick Metrics & Conversion Health Card -->\r\n");
      out.write("      <div class=\"chart-card\" style=\"justify-content: space-between;\">\r\n");
      out.write("        <div>\r\n");
      out.write("          <div class=\"chart-card-header\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <h3 class=\"chart-card-title\">Chỉ số Vận hành Cửa hàng</h3>\r\n");
      out.write("              <p class=\"chart-card-subtitle\">Tỷ số hiệu quả kinh doanh</p>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <div style=\"display:flex; flex-direction:column; gap:16px; margin-top:10px;\">\r\n");
      out.write("            ");
 
              double avgOrderValue = 0.0;
              int ordersCount = (Integer)request.getAttribute("totalOrders");
              double revVal = (Double)request.getAttribute("totalRevenue");
              if (ordersCount > 0) {
                  avgOrderValue = revVal / ordersCount;
              }
            
      out.write("\r\n");
      out.write("            <div style=\"padding:14px 18px; background:var(--bg-board); border-radius:12px; border:1px solid rgba(197,137,64,0.18); display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-size:0.8rem; font-weight:700; color:var(--text-secondary); text-transform:uppercase;\">Giá trị đơn trung bình (AOV)</div>\r\n");
      out.write("                <div style=\"font-size:1.3rem; font-weight:800; color:var(--text-primary); margin-top:2px;\">\r\n");
      out.write("                  ");
      out.print( String.format("%,.0f đ", avgOrderValue) );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div style=\"font-size:1.5rem;\">💳</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"padding:14px 18px; background:var(--bg-board); border-radius:12px; border:1px solid rgba(197,137,64,0.18); display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-size:0.8rem; font-weight:700; color:var(--text-secondary); text-transform:uppercase;\">Tình trạng kho hàng</div>\r\n");
      out.write("                <div style=\"font-size:1.3rem; font-weight:800; color:#059669; margin-top:2px;\">\r\n");
      out.write("                  ");
      out.print( (Integer)request.getAttribute("totalStock") > 0 ? "Còn Hàng & Sẵn Sàng" : "Cần Nhập Thêm" );
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div style=\"font-size:1.5rem;\">📦</div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div style=\"padding:14px 18px; background:var(--bg-board); border-radius:12px; border:1px solid rgba(197,137,64,0.18); display:flex; justify-content:space-between; align-items:center;\">\r\n");
      out.write("              <div>\r\n");
      out.write("                <div style=\"font-size:0.8rem; font-weight:700; color:var(--text-secondary); text-transform:uppercase;\">Hệ thống Quản trị</div>\r\n");
      out.write("                <div style=\"font-size:1.1rem; font-weight:700; color:var(--accent-hover); margin-top:2px;\">\r\n");
      out.write("                  Đồng Bộ Dữ Liệu Trực Tiếp\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div style=\"font-size:1.5rem;\">⚡</div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"margin-top:20px; text-align:center;\">\r\n");
      out.write("          <a href=\"storebooks\" class=\"btn-auth-submit\" style=\"text-decoration:none; padding:11px 20px; font-size:0.92rem;\">\r\n");
      out.write("            <span>Quản Lý Kho Sách Cửa Hàng</span> &rarr;\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tables Row: Low Stock Alerts & Recent Orders -->\r\n");
      out.write("    <div class=\"stats-tables-row\">\r\n");
      out.write("      <!-- Low Stock Alerts Table -->\r\n");
      out.write("      <div class=\"chart-card\">\r\n");
      out.write("        <div class=\"chart-card-header\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3 class=\"chart-card-title\">⚠️ Cảnh Báo Sắp Hết Hàng (≤ 5 cuốn)</h3>\r\n");
      out.write("            <p class=\"chart-card-subtitle\">Các đầu sách cần bổ sung số lượng trong kho</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"addbook\" class=\"nav-pill-btn\" style=\"font-size:0.8rem; padding:6px 14px;\">+ Nhập thêm</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("          <table class=\"table table-hover align-middle\" style=\"margin:0; font-size:0.9rem;\">\r\n");
      out.write("            <thead style=\"background:var(--shelf-surface);\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th style=\"padding:10px 14px;\">Tựa sách</th>\r\n");
      out.write("                <th style=\"padding:10px 14px;\">Đơn giá</th>\r\n");
      out.write("                <th style=\"padding:10px 14px; text-align:center;\">Tồn kho</th>\r\n");
      out.write("                <th style=\"padding:10px 14px; text-align:center;\">Thao tác</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              ");

                List<Map<String, Object>> lowStock = (List<Map<String, Object>>) request.getAttribute("lowStockBooks");
                if (lowStock == null || lowStock.isEmpty()) {
              
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td colspan=\"4\" class=\"text-center py-4\" style=\"color:var(--text-secondary);\">\r\n");
      out.write("                    🎉 <strong>Tuyệt vời!</strong> Tất cả các đầu sách hiện đều có lượng tồn kho dồi dào.\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              ");

                } else {
                  for (Map<String, Object> b : lowStock) {
              
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td style=\"vertical-align:middle; padding:12px 14px;\">\r\n");
      out.write("                    <div style=\"font-weight:700; color:var(--text-primary);\">");
      out.print( b.get("name") );
      out.write("</div>\r\n");
      out.write("                    <div style=\"font-size:0.78rem; color:var(--text-secondary);\">");
      out.print( b.get("author") );
      out.write("</div>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; font-weight:700; color:var(--accent-hover); padding:12px 14px;\">\r\n");
      out.write("                    ");
      out.print( String.format("%,.0f đ", (Double)b.get("price")) );
      out.write("\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; text-align:center; padding:12px 14px;\">\r\n");
      out.write("                    <span class=\"badge-low-stock-urgent\">\r\n");
      out.write("                      Còn ");
      out.print( b.get("quantity") );
      out.write(" cuốn\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; text-align:center; padding:12px 14px;\">\r\n");
      out.write("                    <form method=\"post\" action=\"updatebook\" style=\"margin:0;\">\r\n");
      out.write("                      <input type=\"hidden\" name=\"bookId\" value=\"");
      out.print( b.get("barcode") );
      out.write("\">\r\n");
      out.write("                      <button type=\"submit\" class=\"nav-pill-btn\" style=\"padding:5px 12px; font-size:0.8rem; background:var(--accent-primary); color:#fff; border-color:var(--accent-primary); cursor:pointer;\">Cập nhật</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              ");

                  }
                }
              
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <!-- Recent Orders Table -->\r\n");
      out.write("      <div class=\"chart-card\">\r\n");
      out.write("        <div class=\"chart-card-header\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h3 class=\"chart-card-title\">🕒 Đơn Hàng Gần Đây</h3>\r\n");
      out.write("            <p class=\"chart-card-subtitle\">Các giao dịch mua sách mới nhất</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"orders\" class=\"nav-pill-btn\" style=\"font-size:0.8rem; padding:6px 14px;\">Tất cả đơn &rarr;</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"table-responsive\">\r\n");
      out.write("          <table class=\"table table-hover align-middle\" style=\"margin:0; font-size:0.9rem;\">\r\n");
      out.write("            <thead style=\"background:var(--shelf-surface);\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th style=\"padding:10px 14px;\">Mã đơn</th>\r\n");
      out.write("                <th style=\"padding:10px 14px;\">Khách hàng</th>\r\n");
      out.write("                <th style=\"padding:10px 14px;\">Tổng tiền</th>\r\n");
      out.write("                <th style=\"padding:10px 14px; text-align:center;\">Trạng thái</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              ");

                List<Map<String, Object>> recOrders = (List<Map<String, Object>>) request.getAttribute("recentOrders");
                if (recOrders == null || recOrders.isEmpty()) {
              
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td colspan=\"4\" class=\"text-center py-4\" style=\"color:var(--text-secondary);\">\r\n");
      out.write("                    Chưa có đơn hàng nào. Đơn sẽ hiển thị tại đây ngay khi khách đặt sách.\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              ");

                } else {
                  for (Map<String, Object> o : recOrders) {
                    String st = (String) o.get("status");
                    String badgeClass = "status-paid";
                    String stVi = "ĐÃ THANH TOÁN";
                    if ("PROCESSING".equalsIgnoreCase(st)) {
                        badgeClass = "status-processing";
                        stVi = "ĐANG XỬ LÝ";
                    } else if ("SHIPPED".equalsIgnoreCase(st)) {
                        stVi = "ĐÃ GIAO HÀNG";
                    } else if ("CANCELLED".equalsIgnoreCase(st)) {
                        stVi = "ĐÃ HỦY";
                    }
              
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td style=\"vertical-align:middle; padding:12px 14px;\">\r\n");
      out.write("                    <div style=\"font-weight:700; font-family:monospace;\">");
      out.print( o.get("orderId") );
      out.write("</div>\r\n");
      out.write("                    <div style=\"font-size:0.76rem; color:var(--text-secondary);\">");
      out.print( o.get("orderDate") );
      out.write("</div>\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; padding:12px 14px; font-weight:600;\">\r\n");
      out.write("                    ");
      out.print( o.get("username") );
      out.write("\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; font-weight:700; color:#059669; padding:12px 14px;\">\r\n");
      out.write("                    ");
      out.print( String.format("%,.0f đ", (Double)o.get("totalAmount")) );
      out.write("\r\n");
      out.write("                  </td>\r\n");
      out.write("                  <td style=\"vertical-align:middle; text-align:center; padding:12px 14px;\">\r\n");
      out.write("                    <span class=\"badge-order-status-pill ");
      out.print( badgeClass );
      out.write("\">\r\n");
      out.write("                      ");
      out.print( stVi );
      out.write("\r\n");
      out.write("                    </span>\r\n");
      out.write("                  </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("              ");

                  }
                }
              
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<!-- Chart.js Configuration Scripts -->\r\n");
      out.write("<script>\r\n");
      out.write("document.addEventListener(\"DOMContentLoaded\", function() {\r\n");
      out.write("    // 1. Spline Area Chart: Revenue Trend\r\n");
      out.write("    var revDates = ");
      out.print( request.getAttribute("revenueDatesJson") );
      out.write(";\r\n");
      out.write("    var revAmounts = ");
      out.print( request.getAttribute("revenueAmountsJson") );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("    var revCanvas = document.getElementById('revenueSplineChart');\r\n");
      out.write("    if (revCanvas) {\r\n");
      out.write("        var ctx = revCanvas.getContext('2d');\r\n");
      out.write("        \r\n");
      out.write("        // Golden gradient fill\r\n");
      out.write("        var gradient = ctx.createLinearGradient(0, 0, 0, 260);\r\n");
      out.write("        gradient.addColorStop(0, 'rgba(197, 137, 64, 0.45)');\r\n");
      out.write("        gradient.addColorStop(0.7, 'rgba(197, 137, 64, 0.12)');\r\n");
      out.write("        gradient.addColorStop(1, 'rgba(197, 137, 64, 0.0)');\r\n");
      out.write("\r\n");
      out.write("        new Chart(ctx, {\r\n");
      out.write("            type: 'line',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: revDates,\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Revenue (đ)',\r\n");
      out.write("                    data: revAmounts,\r\n");
      out.write("                    borderColor: '#C58940',\r\n");
      out.write("                    borderWidth: 3,\r\n");
      out.write("                    pointBackgroundColor: '#AE7634',\r\n");
      out.write("                    pointBorderColor: '#ffffff',\r\n");
      out.write("                    pointBorderWidth: 2,\r\n");
      out.write("                    pointRadius: 5,\r\n");
      out.write("                    pointHoverRadius: 7,\r\n");
      out.write("                    tension: 0.38,\r\n");
      out.write("                    fill: true,\r\n");
      out.write("                    backgroundColor: gradient\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                maintainAspectRatio: false,\r\n");
      out.write("                interaction: {\r\n");
      out.write("                    intersect: false,\r\n");
      out.write("                    mode: 'index',\r\n");
      out.write("                },\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        display: false\r\n");
      out.write("                    },\r\n");
      out.write("                    tooltip: {\r\n");
      out.write("                        backgroundColor: 'rgba(28, 24, 21, 0.92)',\r\n");
      out.write("                        titleFont: { family: 'Plus Jakarta Sans', size: 13 },\r\n");
      out.write("                        bodyFont: { family: 'Plus Jakarta Sans', size: 12 },\r\n");
      out.write("                        padding: 12,\r\n");
      out.write("                        cornerRadius: 10,\r\n");
      out.write("                        callbacks: {\r\n");
      out.write("                            label: function(context) {\r\n");
      out.write("                                return ' Doanh thu: ' + context.parsed.y.toLocaleString('vi-VN') + ' đ';\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                scales: {\r\n");
      out.write("                    x: {\r\n");
      out.write("                        grid: { display: false },\r\n");
      out.write("                        ticks: {\r\n");
      out.write("                            font: { family: 'Plus Jakarta Sans', weight: '600' },\r\n");
      out.write("                            color: '#7C746B'\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    y: {\r\n");
      out.write("                        beginAtZero: true,\r\n");
      out.write("                        grid: {\r\n");
      out.write("                            color: 'rgba(197, 137, 64, 0.1)'\r\n");
      out.write("                        },\r\n");
      out.write("                        ticks: {\r\n");
      out.write("                            font: { family: 'Plus Jakarta Sans' },\r\n");
      out.write("                            color: '#7C746B',\r\n");
      out.write("                            callback: function(value) {\r\n");
      out.write("                                if (value >= 1000000) return (value / 1000000) + 'M đ';\r\n");
      out.write("                                if (value >= 1000) return (value / 1000) + 'k đ';\r\n");
      out.write("                                return value + ' đ';\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 2. Doughnut Chart: Order Status Distribution\r\n");
      out.write("    var statusLabels = ");
      out.print( request.getAttribute("statusLabelsJson") );
      out.write(";\r\n");
      out.write("    var statusCounts = ");
      out.print( request.getAttribute("statusCountsJson") );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("    var statusCanvas = document.getElementById('orderStatusDoughnutChart');\r\n");
      out.write("    if (statusCanvas) {\r\n");
      out.write("        new Chart(statusCanvas, {\r\n");
      out.write("            type: 'doughnut',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: statusLabels,\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    data: statusCounts,\r\n");
      out.write("                    backgroundColor: [\r\n");
      out.write("                        '#10B981', // Emerald PAID\r\n");
      out.write("                        '#3B82F6', // Blue PROCESSING\r\n");
      out.write("                        '#F59E0B', // Amber SHIPPED\r\n");
      out.write("                        '#8B5CF6', // Purple COMPLETED\r\n");
      out.write("                        '#EF4444'  // Red CANCELLED\r\n");
      out.write("                    ],\r\n");
      out.write("                    borderWidth: 3,\r\n");
      out.write("                    borderColor: '#ffffff',\r\n");
      out.write("                    hoverOffset: 6\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                maintainAspectRatio: false,\r\n");
      out.write("                cutout: '68%',\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: {\r\n");
      out.write("                        position: 'bottom',\r\n");
      out.write("                        labels: {\r\n");
      out.write("                            font: { family: 'Plus Jakarta Sans', weight: '600', size: 12 },\r\n");
      out.write("                            color: '#2B2825',\r\n");
      out.write("                            padding: 14,\r\n");
      out.write("                            usePointStyle: true\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    tooltip: {\r\n");
      out.write("                        backgroundColor: 'rgba(28, 24, 21, 0.92)',\r\n");
      out.write("                        cornerRadius: 10,\r\n");
      out.write("                        padding: 10\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 3. Horizontal Bar Chart: Top 5 Bestsellers\r\n");
      out.write("    var topNames = ");
      out.print( request.getAttribute("topNamesJson") );
      out.write(";\r\n");
      out.write("    var topSales = ");
      out.print( request.getAttribute("topSalesJson") );
      out.write(";\r\n");
      out.write("\r\n");
      out.write("    var topCanvas = document.getElementById('topBooksBarChart');\r\n");
      out.write("    if (topCanvas) {\r\n");
      out.write("        new Chart(topCanvas, {\r\n");
      out.write("            type: 'bar',\r\n");
      out.write("            data: {\r\n");
      out.write("                labels: topNames,\r\n");
      out.write("                datasets: [{\r\n");
      out.write("                    label: 'Số lượng bán (cuốn)',\r\n");
      out.write("                    data: topSales,\r\n");
      out.write("                    backgroundColor: 'rgba(197, 137, 64, 0.85)',\r\n");
      out.write("                    hoverBackgroundColor: '#AE7634',\r\n");
      out.write("                    borderRadius: 8,\r\n");
      out.write("                    borderSkipped: false,\r\n");
      out.write("                    barThickness: 24\r\n");
      out.write("                }]\r\n");
      out.write("            },\r\n");
      out.write("            options: {\r\n");
      out.write("                indexAxis: 'y',\r\n");
      out.write("                responsive: true,\r\n");
      out.write("                maintainAspectRatio: false,\r\n");
      out.write("                plugins: {\r\n");
      out.write("                    legend: { display: false },\r\n");
      out.write("                    tooltip: {\r\n");
      out.write("                        backgroundColor: 'rgba(28, 24, 21, 0.92)',\r\n");
      out.write("                        cornerRadius: 10,\r\n");
      out.write("                        padding: 10,\r\n");
      out.write("                        callbacks: {\r\n");
      out.write("                            label: function(context) {\r\n");
      out.write("                                return ' Đã bán: ' + context.parsed.x + ' cuốn';\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("                scales: {\r\n");
      out.write("                    x: {\r\n");
      out.write("                        beginAtZero: true,\r\n");
      out.write("                        grid: { color: 'rgba(197, 137, 64, 0.08)' },\r\n");
      out.write("                        ticks: {\r\n");
      out.write("                            font: { family: 'Plus Jakarta Sans' },\r\n");
      out.write("                            color: '#7C746B',\r\n");
      out.write("                            stepSize: 1\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    y: {\r\n");
      out.write("                        grid: { display: false },\r\n");
      out.write("                        ticks: {\r\n");
      out.write("                            font: { family: 'Plus Jakarta Sans', weight: '600', size: 12 },\r\n");
      out.write("                            color: '#2B2825'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
